# MCU := RP2040
# BOARD := QMK_PM2040
# BOOTLOADER := rp2040

CONVERT_TO = rp2040_ce
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
OLED_ENABLE = no

RGB_MATRIX_ENABLE = yes
VIALRGB_ENABLE = yes
VIA_ENABLE = yes
VIAL_ENABLE = yes

LTO_ENABLE = no
NKRO_ENABLE = yes
COMBO_ENABLE = yes
QMK_SETTINGS = yes

QUANTUM_PAINTER_ENABLE = yes
QUANTUM_PAINTER_DRIVERS += st7789_spi
SRC += display.c
CONSOLE_ENABLE = no
SPI_DRIVER_REQUIRED = yes

